name: App workflow
on:
  push:
    branches:
      - '*'
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    container: node:10.16.3-alpine
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - name: Run test
        run: yarn test --watchAll
